# Generated by Django 4.2 on 2023-04-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0002_alter_subscription_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="options",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly")], default="W", max_length=2
            ),
            preserve_default=False,
        ),
    ]
