# Generated by Django 4.2 on 2023-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20230423_0242"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="description",
            new_name="discription",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
