# Generated by Django 4.2 on 2023-04-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_description_jobpost_discription_jobpost_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="discription",
            new_name="description",
        ),
    ]
