# Generated by Django 4.2 on 2023-04-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_author_jobpost_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="degisnation",
            new_name="designation",
        ),
    ]
